TestGitHub/TestGitHub/Models/Repartidor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
#nullable disable
namespace TestGitHub.Models
{
    public partial class Repartidor
    {
        public uint IdRepartidor { get; set; }
        [Required(ErrorMessage = "El campo Nombre debe ser llenado.")]
        public string NombreRepartidor { get; set; } = null!;
        [Required(ErrorMessage = "El campo Apellido debe ser llenado.")]
        public string ApellidoRepartidor { get; set; } = null!;
    }
}

TestGitHub/TestGitHub/Controllers/RepartidorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.X509Certificates;
using TestGitHub.Utilidades;

namespace TestGitHub.Controllers
{
    public class RepartidorController : Controller
    {
        private readonly bdproductoContext Context;
        public RepartidorController(bdproductoContext context)
        {
            Context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Route("Repartidor/ope/listar")]
        public IActionResult ListarRepartidores()
        {
            var ObjSesion = HttpContext.Session.Get<Cliente>("scliente");
            if (ObjSesion != null)
            {
                var list = Context.Repartidors;
                return View(list);
            }
            else
            {
                return RedirectToAction("Index", "Cliente");
            }
        }
        public IActionResult Registro()
        {
            var ObjSesion = HttpContext.Session.Get<Cliente>("scliente");
            if (ObjSesion != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Cliente");
            }
        }
        public IActionResult RegistrarRepartidor(Repartidor obj)
        {
            if (ModelState.IsValid)
            {
                Context.Repartidors.Add(obj);
                Context.SaveChanges();
                return RedirectToAction("ListarRepartidores");
            }
            else
            {
                return RedirectToAction("Registro");
            }
        }
        [Route("Repartidor/Edit/{codigo}")]
        public IActionResult Edit(int codigo)
        {
            var ObjSesion = HttpContext.Session.Get<Cliente>("scliente");
            if (ObjSesion != null)
            {
                var Obj = (from TRepartidor in Context.Repartidors
                           where TRepartidor.IdRepartidor == codigo
                           select TRepartidor).Single();

                return View(Obj);
            }
            else
            {
                return RedirectToAction("Index", "Cliente");
            }
        }

        public IActionResult EditarRepartidores(Repartidor ObjNew)
        {
            if (ModelState.IsValid)
            {
                var ObjOld = (from TRepartidor in Context.Repartidors
                              where TRepartidor.IdRepartidor == ObjNew.IdRepartidor
                              select TRepartidor).Single();

                ObjOld.IdRepartidor = ObjNew.IdRepartidor;
                ObjOld.NombreRepartidor = ObjNew.NombreRepartidor;
                ObjOld.ApellidoRepartidor = ObjNew.ApellidoRepartidor;

                Context.SaveChanges();
                return RedirectToAction("ListarRepartidores");
            }
            else
            {
                return View("Edit");
            }         
        }
        [Route("Repartidor/Delete/{Codigo}")]
        public IActionResult Delete(int codigo)
        {
            var Obj = (from TRepartidor in Context.Repartidors
                       where TRepartidor.IdRepartidor == codigo
                       select TRepartidor).Single();

            Context.Repartidors.Remove(Obj);
            Context.SaveChanges();
            return RedirectToAction("ListarRepartidores");
        }
    }
}

TestGitHub/TestGitHub/Views/Repartidor/Edit.cshtml
@model TestGitHub.Models.Repartidor
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Editar repartirdores</title>
        <link rel="stylesheet" href="../css/estilosRegistro.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@100&display=swap" rel="stylesheet">
    </head>
    <body>
        <form asp-controller="Repartidor" asp-action="EditarRepartidores" method="post">
            <div class="form-group">
                <label hidden="hidden" for="formGroupExampleInput">Id</label>
                <input hidden="hidden" asp-for="IdRepartidor" class="form-control" id="formGroupExampleInput" placeholder="Ingrese sus nombres">
                <span hidden="hidden" asp-validation-for="IdRepartidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput">Nombres</label>
                <input asp-for="NombreRepartidor" class="form-control" id="formGroupExampleInput" placeholder="Ingrese sus nombres">
                <span asp-validation-for="NombreRepartidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput">Apellidos</label>
                <input asp-for="ApellidoRepartidor" class="form-control" id="formGroupExampleInput" placeholder="Ingrese sus apellidos">
                <span asp-validation-for="ApellidoRepartidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" value="btn" name="grabar" data-toggle="modal" data-target="#exampleModal">Grabar</button>
            </div>

        </form>
    </body>
</html>
@section Scripts{
    @{
        <partial name="_ValidationSCriptsPartial" />}
}

TestGitHub/TestGitHub/Views/Repartidor/ListarRepartidores.cshtml
@model IEnumerable<TestGitHub.Models.Repartidor>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<html>
    <body>
        <h1><a asp-controller="Repartidor" asp-action="RegistrarRepartidor">Añadir repartidor</a></h1>
        <h2>
            Buscar<input type="text" class="form-control" id="myInput" placeholder="Search..." />
        </h2>
        <table class="table table-bordered">
            <tr>
                <td scope="col">ID</td>
                <td scope="col">Nombres</td>
                <td scope="col">Apellido</td>
            </tr>
            <tbody id="myTable">
            @foreach(var item in Model)
            {
                <tr>
                    <td scope="col">@item.IdRepartidor</td>
                    <td scope="col">@item.NombreRepartidor</td>
                    <td scope="col">@item.ApellidoRepartidor</td>
                    <td scope="col"><a asp-action="Edit" asp-route-id="@item.IdRepartidor">Editar</a></td>
                    <td scope="col"><a asp-action="Delete" asp-route-id="@item.IdRepartidor">Eliminar</a></td>
                </tr>
            }
            </tbody>
        </table>
    </body>    
</html>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

TestGitHub/TestGitHub/Views/Repartidor/Registro.cshtml
@model TestGitHub.Models.Repartidor
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registro de repartirdor</title>
        <link rel="stylesheet" href="../css/estilosRegistro.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@100&display=swap" rel="stylesheet">
    </head>
    <body>
        <form asp-controller="Repartidor" asp-action="RegistrarRepartidor" method="post">
            <div class="form-group">
                <label for="formGroupExampleInput">Nombres</label>
                <input asp-for="NombreRepartidor" class="form-control" id="formGroupExampleInput" placeholder="Ingrese sus nombres">
                <span asp-validation-for="NombreRepartidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput">Apellidos</label>
                <input asp-for="ApellidoRepartidor" class="form-control" id="formGroupExampleInput" placeholder="Ingrese sus apellidos">
                <span asp-validation-for="ApellidoRepartidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" value="btn" name="grabar" data-toggle="modal" data-target="#exampleModal">Grabar</button>
            </div>

        </form>
    </body>
</html>

@section Scripts{
    @{
        <partial name="_ValidationSCriptsPartial" />}
}